### ISSUE TITLE
Package namespace issues

### ISSUE THREAD

**Issue by dcolligan** [BD2KGenomics/ga4gh-integration#38]
Right now, we have the `ga4gh_client` and `ga4gh` packages.  Eventually all packages should be able to be imported by the following syntax:

`import ga4gh.foo`

Where foo is client, server, schemas, whatever.

**Comment by david4096** [comment]
Yeah, let's use a single namespace `ga4gh`. To add a module to a namespace you can use `pkgutil` http://stackoverflow.com/questions/1675734/how-do-i-create-a-namespace-package-in-python

Since we have the client moved out, we should work to satisfy https://github.com/ga4gh/schemas/issues/721 first. Then we can replace the process schemas and shared code between the client and server.

**Comment by dcolligan** [comment]
Fixed a long time ago... closing...
